# coding: utf-8

# flake8: noqa
"""
    Community Digital Voting System

    Vote on community proposals with deadlines and revocation support.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from voting_sdk.models.http_validation_error import HTTPValidationError
from voting_sdk.models.location_inner import LocationInner
from voting_sdk.models.proposal_create import ProposalCreate
from voting_sdk.models.proposal_detail import ProposalDetail
from voting_sdk.models.proposal_read import ProposalRead
from voting_sdk.models.proposal_status import ProposalStatus
from voting_sdk.models.validation_error import ValidationError
from voting_sdk.models.vote_choice import VoteChoice
from voting_sdk.models.vote_counts import VoteCounts
from voting_sdk.models.vote_create import VoteCreate
from voting_sdk.models.vote_read import VoteRead

