# coding: utf-8

"""
    Community Digital Voting System

    Vote on community proposals with deadlines and revocation support.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from voting_sdk.models.proposal_status import ProposalStatus
from voting_sdk.models.vote_counts import VoteCounts
from voting_sdk.models.vote_read import VoteRead
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProposalDetail(BaseModel):
    """
    ProposalDetail
    """ # noqa: E501
    id: StrictInt
    title: StrictStr
    description: StrictStr
    created_at: datetime
    deadline: datetime
    status: ProposalStatus
    counts: VoteCounts
    votes: Optional[List[VoteRead]] = None
    __properties: ClassVar[List[str]] = ["id", "title", "description", "created_at", "deadline", "status", "counts", "votes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProposalDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of counts
        if self.counts:
            _dict['counts'] = self.counts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in votes (list)
        _items = []
        if self.votes:
            for _item_votes in self.votes:
                if _item_votes:
                    _items.append(_item_votes.to_dict())
            _dict['votes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProposalDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "created_at": obj.get("created_at"),
            "deadline": obj.get("deadline"),
            "status": obj.get("status"),
            "counts": VoteCounts.from_dict(obj["counts"]) if obj.get("counts") is not None else None,
            "votes": [VoteRead.from_dict(_item) for _item in obj["votes"]] if obj.get("votes") is not None else None
        })
        return _obj


