# coding: utf-8

"""
    Community Digital Voting System

    Vote on community proposals with deadlines and revocation support.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class VoteChoice(str, Enum):
    """
    VoteChoice
    """

    """
    allowed enum values
    """
    YES = 'yes'
    NO = 'no'
    ABSTAIN = 'abstain'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VoteChoice from a JSON string"""
        return cls(json.loads(json_str))


