# coding: utf-8

"""
    Community Digital Voting System

    Vote on community proposals with deadlines and revocation support.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voting_sdk.models.proposal_create import ProposalCreate

class TestProposalCreate(unittest.TestCase):
    """ProposalCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProposalCreate:
        """Test ProposalCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProposalCreate`
        """
        model = ProposalCreate()
        if include_optional:
            return ProposalCreate(
                title = '0',
                description = '',
                deadline = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ProposalCreate(
                title = '0',
        )
        """

    def testProposalCreate(self):
        """Test ProposalCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
