# coding: utf-8

"""
    Community Digital Voting System

    Vote on community proposals with deadlines and revocation support.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voting_sdk.api.votes_api import VotesApi


class TestVotesApi(unittest.TestCase):
    """VotesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VotesApi()

    def tearDown(self) -> None:
        pass

    def test_revoke_vote_votes_vote_id_delete(self) -> None:
        """Test case for revoke_vote_votes_vote_id_delete

        Revoke Vote
        """
        pass


if __name__ == '__main__':
    unittest.main()
