# coding: utf-8

"""
    Community Digital Voting System

    Vote on community proposals with deadlines and revocation support.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voting_sdk.models.proposal_status import ProposalStatus

class TestProposalStatus(unittest.TestCase):
    """ProposalStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProposalStatus(self):
        """Test ProposalStatus"""
        # inst = ProposalStatus()

if __name__ == '__main__':
    unittest.main()
