# coding: utf-8

"""
    Community Digital Voting System

    Vote on community proposals with deadlines and revocation support.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voting_sdk.models.proposal_detail import ProposalDetail

class TestProposalDetail(unittest.TestCase):
    """ProposalDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProposalDetail:
        """Test ProposalDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProposalDetail`
        """
        model = ProposalDetail()
        if include_optional:
            return ProposalDetail(
                id = 56,
                title = '',
                description = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deadline = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'active',
                counts = voting_sdk.models.vote_counts.VoteCounts(
                    yes = 56, 
                    no = 56, 
                    abstain = 56, 
                    total = 56, ),
                votes = [
                    voting_sdk.models.vote_read.VoteRead(
                        id = 56, 
                        proposal_id = 56, 
                        voter_name = '', 
                        vote = 'yes', 
                        voted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ProposalDetail(
                id = 56,
                title = '',
                description = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deadline = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'active',
                counts = voting_sdk.models.vote_counts.VoteCounts(
                    yes = 56, 
                    no = 56, 
                    abstain = 56, 
                    total = 56, ),
        )
        """

    def testProposalDetail(self):
        """Test ProposalDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
