# coding: utf-8

"""
    Community Digital Voting System

    Vote on community proposals with deadlines and revocation support.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voting_sdk.api.proposals_api import ProposalsApi


class TestProposalsApi(unittest.TestCase):
    """ProposalsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProposalsApi()

    def tearDown(self) -> None:
        pass

    def test_close_proposal_proposals_proposal_id_close_patch(self) -> None:
        """Test case for close_proposal_proposals_proposal_id_close_patch

        Close Proposal
        """
        pass

    def test_create_proposal_proposals_post(self) -> None:
        """Test case for create_proposal_proposals_post

        Create Proposal
        """
        pass

    def test_get_proposal_proposals_proposal_id_get(self) -> None:
        """Test case for get_proposal_proposals_proposal_id_get

        Get Proposal
        """
        pass

    def test_list_proposals_proposals_get(self) -> None:
        """Test case for list_proposals_proposals_get

        List Proposals
        """
        pass

    def test_vote_on_proposal_proposals_proposal_id_vote_post(self) -> None:
        """Test case for vote_on_proposal_proposals_proposal_id_vote_post

        Vote On Proposal
        """
        pass


if __name__ == '__main__':
    unittest.main()
