# coding: utf-8

"""
    Community Digital Voting System

    Vote on community proposals with deadlines and revocation support.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voting_sdk.models.vote_counts import VoteCounts

class TestVoteCounts(unittest.TestCase):
    """VoteCounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoteCounts:
        """Test VoteCounts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoteCounts`
        """
        model = VoteCounts()
        if include_optional:
            return VoteCounts(
                yes = 56,
                no = 56,
                abstain = 56,
                total = 56
            )
        else:
            return VoteCounts(
        )
        """

    def testVoteCounts(self):
        """Test VoteCounts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
